FROM nvcr.io/nvidia/deepstream:6.1-devel as build
RUN apt-get update && apt-get install --fix-broken -y \
    python3-gi \
    python3-dev \
    python3-gst-1.0 \
    python-gi-dev \
    git python-dev \
    python3 \
    python3-pip \
    python3.8-dev \
    cmake g++ \
    build-essential \
    libglib2.0-dev \
    libglib2.0-dev-bin \
    libgstreamer1.0-dev \
    libtool \
    m4 \
    autoconf \
    automake \
    libgirepository1.0-dev \
    libcairo2-dev \
    libjson-glib-dev \
    libgstreamer-plugins-base1.0-dev \
    libpython3-dev \
    libopencv-dev \
    libspdlog-dev \
    supervisor

RUN apt-get remove -y gstreamer1.0-plugins-ugly

COPY dependency /opt/nvidia/deepstream/deepstream-6.1/sources/temp
COPY requirements.txt /opt/nvidia/deepstream/deepstream-6.1/sources/temp
WORKDIR /opt/nvidia/deepstream/deepstream-6.1/sources/temp
RUN pip3 install -i https://pypi.mirrors.ustc.edu.cn/simple/  -r requirements.txt
RUN cp -r /usr/local/lib/python3.8/site-packages/wsdl /usr/local/lib/python3.8/dist-packages/

WORKDIR /opt/nvidia/deepstream/deepstream-6.1/sources/temp/3rdparty/gst-python
# RUN git config --global http.version HTTP/1.1
RUN chmod u+x ./autogen.sh
RUN ./autogen.sh PYTHON=python3
RUN ./configure PYTHON=python3
RUN make && make install

RUN mkdir -p /opt/nvidia/deepstream/deepstream-6.1/sources/temp/bindings/build
WORKDIR /opt/nvidia/deepstream/deepstream-6.1/sources/temp/bindings/build
RUN cmake ..
RUN make
RUN pip3 install ./pyds-1.1.4-py3-none*.whl -i https://pypi.mirrors.ustc.edu.cn/simple/

